os: linux
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36,docs-html
#    - python: 3.6
#      env: TOXENV=integration-test
    - python: 3.6
      env: TOXENV=sample-test
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 2.7
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py27

before_install: |
  # Install Rust
  curl https://sh.rustup.rs -sSf | bash -s -- -y
  export PATH="/usr/local/bin:$HOME/.cargo/bin:$PATH"
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update || brew update

    brew outdated openssl || brew upgrade openssl
    brew install openssl@1.1

    # install pyenv
    git clone --depth 1 https://github.com/pyenv/pyenv ~/.pyenv
    PYENV_ROOT="$HOME/.pyenv"
    PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"

    case "${TOXENV}" in
      py27)
        curl -O https://bootstrap.pypa.io/get-pip.py
        python get-pip.py --user
        ;;
      py36)
        pyenv install 3.6.1
        pyenv global 3.6.1
        ;;
    esac
    pyenv rehash
    # A manual check that the correct version of Python is running.
    python --version
  fi

install:
  - python -m pip install tox

script:
  - tox

after_success:
  - tox -e codecov
  - codecov

cache:
  - pip